# Generated by Django 4.0.2 on 2022-03-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contact_nummber',
            new_name='contact_number',
        ),
    ]
